//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesGeneral : DbContext
    {
        public EntitiesGeneral()
            : base("name=EntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<CatalogoTipo> CatalogoTipo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Subasta> Subasta { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioPerfil> UsuarioPerfil { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<VWRPT_001> VWRPT_001 { get; set; }
    
        public virtual ObjectResult<SPRPT_002_Result> SPRPT_002(Nullable<int> idProveedorIni, Nullable<int> idProveedorFin, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var idProveedorIniParameter = idProveedorIni.HasValue ?
                new ObjectParameter("IdProveedorIni", idProveedorIni) :
                new ObjectParameter("IdProveedorIni", typeof(int));
    
            var idProveedorFinParameter = idProveedorFin.HasValue ?
                new ObjectParameter("IdProveedorFin", idProveedorFin) :
                new ObjectParameter("IdProveedorFin", typeof(int));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPRPT_002_Result>("SPRPT_002", idProveedorIniParameter, idProveedorFinParameter, fechaIniParameter, fechaFinParameter);
        }
    }
}
