//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaDet
    {
        public decimal IdOferta { get; set; }
        public int Secuencia { get; set; }
        public double od_Cantidad { get; set; }
        public double od_PrecioUni { get; set; }
        public double od_PorDescuento { get; set; }
        public double od_DescuentoUni { get; set; }
        public double od_PrecioFinal { get; set; }
        public double od_Subtotal { get; set; }
        public int IdImpuesto { get; set; }
        public double od_Porcentaje { get; set; }
        public double od_Iva { get; set; }
        public double od_Total { get; set; }
        public string od_Observacion { get; set; }
    
        public virtual Impuesto Impuesto { get; set; }
        public virtual Oferta Oferta { get; set; }
    }
}
