//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public decimal IdOferta { get; set; }
        public decimal IdSubasta { get; set; }
        public decimal IdProveedor { get; set; }
        public string of_Observacion { get; set; }
        public bool of_Estado { get; set; }
        public System.DateTime of_Fecha { get; set; }
        public System.DateTime of_FechaFin { get; set; }
        public int of_Plazo { get; set; }
        public bool of_EstadoGanador { get; set; }
        public double of_Total { get; set; }
    
        public virtual Subasta Subasta { get; set; }
    }
}
