//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Subasta = new HashSet<Subasta>();
        }
    
        public decimal IdProducto { get; set; }
        public string pr_Codigo { get; set; }
        public string pr_Descripcion { get; set; }
        public string pr_Observacion { get; set; }
        public bool pr_Estado { get; set; }
        public int IdGrupo { get; set; }
        public int IdCatalogoTipo { get; set; }
        public int IdCatalogoMarca { get; set; }
        public int IdCatalogoModelo { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual Catalogo Catalogo1 { get; set; }
        public virtual Catalogo Catalogo2 { get; set; }
        public virtual Grupo Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subasta> Subasta { get; set; }
    }
}
