//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public decimal IdProveedor { get; set; }
        public string pv_Codigo { get; set; }
        public string pv_TipoDoc { get; set; }
        public string pv_CedulaRuc { get; set; }
        public string pv_Descripcion { get; set; }
        public string pv_Correo { get; set; }
        public string pv_Telefono { get; set; }
        public string pv_Direccion { get; set; }
        public int pv_Plazo { get; set; }
        public bool pv_Estado { get; set; }
    }
}
