//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProveedorSucursal()
        {
            this.Oferta = new HashSet<Oferta>();
        }
    
        public decimal IdProveedor { get; set; }
        public int Secuencia { get; set; }
        public string ps_CodigoEstablecimiento { get; set; }
        public string ps_Direccion { get; set; }
        public string ps_Telefono { get; set; }
        public string ps_Correo { get; set; }
        public bool ps_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
