//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Auditoria = new HashSet<Auditoria>();
            this.Subasta = new HashSet<Subasta>();
        }
    
        public string IdUsuario { get; set; }
        public string us_Clave { get; set; }
        public string us_Descripcion { get; set; }
        public string us_Correo { get; set; }
        public bool us_Estado { get; set; }
        public bool us_DebeCambiarClave { get; set; }
        public string IdPerfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auditoria> Auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subasta> Subasta { get; set; }
        public virtual UsuarioPerfil UsuarioPerfil { get; set; }
    }
}
